### ISSUE TITLE
翻墙失败，怎么回事？

### ISSUE THREAD

**Issue by luckypoem** [luikore/stochastic-socks#2]
hi。
服务器端：
root@server:~# ps aux|grep server.rb
root      7488  0.0  1.2  58796 12332 ?        Sl   14:20   0:31 ruby server.rb
root     14586  0.0  0.0   6780   988 pts/1    S+   23:05   0:00 grep --color=auto server.rb
root@server:~# cd stochastic-socks
root@server:~/stochastic-socks# cat config.yml
# openssl cipher method
cipher: aes-256-cbc

# used in cipher
key: iloveson

# set to 0.0.0.0 if you want to share
local: 'localhost'

# socks5 port
local_port: 1234

# remote server ip or domain
server: 0.0.0.0

server_port: 6789

# delimiter string, to split ciphered data chunks
delim: 学习十八大精神建设和谐社会
root@server:~/stochastic-socks#

本地的配置文件如下：
bogon:stochastic-socks brite$ cat config.yml
# openssl cipher method
cipher: aes-256-cbc

# used in cipher
key: iloveson

# set to 0.0.0.0 if you want to share
local: 'localhost'

# socks5 port
local_port: 1234

# remote server ip or domain
server: my-vps-ip

server_port: 6789

# delimiter string, to split ciphered data chunks
delim: 学习十八大精神建设和谐社会
bogon:stochastic-socks brite$ ruby local.rb
starting socks5 at localhost:1234

我替浏览器设置了socks代理服务器地址为localhost:1234 ，但是却翻墙失败，怎么回事？

**Comment by luikore** [comment]
先查下是否能连上端口：

```bash
telnet my-vps-ip 6789
```

如果出现

```bash
Connected to my-vps-ip.
Escape character is '^]'.
```

就说明服务器起来了并且能连上. （可以 ctrl + ] 然后 q 回车退出 telnet）

如果没出现上面的响应，可以在 server 上也试一下 `telnet localhost 6789` 和 `telnet 0.0.0.0 6789`.

如果 localhost 可以而 0.0.0.0 不可以，那就是本机端口没开，得用 iptables 设置

如果 0.0.0.0 可以而 my-vps-ip 不可以，那可能是 VPS 的 security group block 了，得去 VPS 改设置

如果 security group 也没问题，那可能是中奖了, 换个端口/IP/机房试试……

**Comment by luckypoem** [comment]
我运行telnet my-vps-ip 6789
确实出现：
Connected to my-vps-ip.
Escape character is '^]'.

把服务器端的配置文件里的server的值改为我vps的ip,还是翻墙失败

**Comment by luckypoem** [comment]
你自己测试过，用你这方法，你确实能翻墙吗

**Comment by luikore** [comment]
我自己用的没问题，但是别人用会碰到各种情况都是可能的……

本地命令行这样能访问吗？

```
ALL_PROXY=socks5://localhost:2791 curl twitter.com
```

如果可以，也有可能是浏览器或者系统配置没对（没选 socksv5）？

如果不行，得 debug 了...

**Comment by luckypoem** [comment]
知道原因了。
原来，本地的配置文件里的local的值如果写为localhost, 则浏览器里的‘代理服务器’一栏的值必须写为localhost,才能成功翻墙；如果浏览器里的‘代理服务器’一栏的值写为127.0.0.1，则翻墙失败。

本地的配置文件里的local的值如果写为127.0.0.1，则浏览器里的‘代理服务器’一栏的值写为localhost或127.0.0.1，均可成功翻墙。

只是没完全搞懂localhost和127.0.0.1的区别，楼主阐述一下区别？

**Comment by luikore** [comment]
哦！那应该是 eventmachine 的 start_server 函数的坑……

程序碰到非 IP 应该先 resolve 的 （一般等于 127.0.0.1, 但是也可以在 /etc/hosts 配置别的）……
